development:
  adapter: postgresql
  encoding: unicode
  database: mm_summer_programs_development
  pool: 5
  username: jordyone
  password: ''

test:
  adapter: postgresql
  encoding: unicode
  database: mm_summer_programs_test
  pool: 5
  username: jordyone
  password: ''
